version: '3.3'

services:
  #service 1: definition of mysql database
#  db:
#    image: mysql:latest
#    container_name: mysqlCloud
#    environment:
#        MYSQL_DATABASE: vitgdbOne
#        MYSQL_HOST: vitgdb.ctpx6vciwga4.ap-south-1.rds.amazonaws.com
#        MYSQL_USER: admin
#        MYSQL_PASSWORD: admin123
#        MYSQL_ROOT_PASSWORD: admin123
#    ports:
#      - "3306:3306"
#    restart: always

  #service 3: definition of your spring-boot app
  customerservice:                        #it is just a name, which will be used only in this file.
    image: vitg/backend:0.0.5              #name of the image after dockerfile executes
    container_name: customer-service-app  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8084:8082"                       #docker containter port with your os port
    restart: always

#    depends_on:                           #define dependencies of this app
#      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://vitgdb.ctpx6vciwga4.ap-south-1.rds.amazonaws.com:3306/vitgdbOne?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_SHOW-SQL: true